[project]
name = "agnoevents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Edrick Lin", email = "edrick.lin28@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "agno>=2.8.7",
    "curl-cffi>=0.16.0",
    "fastapi>=0.141.1",
    "google-genai>=2.17.0",
]

[project.scripts]
agnoevents = "agnoevents:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
